// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.17.3
// source: asn1.proto

package asn1pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Module struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Module) Reset() {
	*x = Module{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asn1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_asn1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_asn1_proto_rawDescGZIP(), []int{0}
}

type ASN1 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Modules []*Module `protobuf:"bytes,1,rep,name=modules,proto3" json:"modules,omitempty"`
}

func (x *ASN1) Reset() {
	*x = ASN1{}
	if protoimpl.UnsafeEnabled {
		mi := &file_asn1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ASN1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASN1) ProtoMessage() {}

func (x *ASN1) ProtoReflect() protoreflect.Message {
	mi := &file_asn1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASN1.ProtoReflect.Descriptor instead.
func (*ASN1) Descriptor() ([]byte, []int) {
	return file_asn1_proto_rawDescGZIP(), []int{1}
}

func (x *ASN1) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

var File_asn1_proto protoreflect.FileDescriptor

var file_asn1_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x73, 0x6e, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x73,
	0x6e, 0x31, 0x70, 0x62, 0x22, 0x08, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x30,
	0x0a, 0x04, 0x41, 0x53, 0x4e, 0x31, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x73, 0x6e, 0x31, 0x70, 0x62,
	0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x07, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73,
	0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74,
	0x68, 0x65, 0x62, 0x61, 0x67, 0x63, 0x68, 0x69, 0x2f, 0x67, 0x6f, 0x79, 0x61, 0x63, 0x63, 0x2d,
	0x73, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x73, 0x6e,
	0x31, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_asn1_proto_rawDescOnce sync.Once
	file_asn1_proto_rawDescData = file_asn1_proto_rawDesc
)

func file_asn1_proto_rawDescGZIP() []byte {
	file_asn1_proto_rawDescOnce.Do(func() {
		file_asn1_proto_rawDescData = protoimpl.X.CompressGZIP(file_asn1_proto_rawDescData)
	})
	return file_asn1_proto_rawDescData
}

var file_asn1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_asn1_proto_goTypes = []interface{}{
	(*Module)(nil), // 0: asn1pb.Module
	(*ASN1)(nil),   // 1: asn1pb.ASN1
}
var file_asn1_proto_depIdxs = []int32{
	0, // 0: asn1pb.ASN1.modules:type_name -> asn1pb.Module
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_asn1_proto_init() }
func file_asn1_proto_init() {
	if File_asn1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_asn1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Module); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_asn1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ASN1); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_asn1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_asn1_proto_goTypes,
		DependencyIndexes: file_asn1_proto_depIdxs,
		MessageInfos:      file_asn1_proto_msgTypes,
	}.Build()
	File_asn1_proto = out.File
	file_asn1_proto_rawDesc = nil
	file_asn1_proto_goTypes = nil
	file_asn1_proto_depIdxs = nil
}
