// Code generated by goyacc -p ASN asn.y. DO NOT EDIT.

//line asn.y:1

package main

import __yyfmt__ "fmt"

//line asn.y:3
import (
	"bytes"
	"encoding/json"
	"fmt"
	"strconv"
)

var code bytes.Buffer

func AddLine(line string) {
	code.WriteString(line)
	code.WriteByte('\n')
}

func JSON(obj interface{}) string {
	data, err := json.MarshalIndent(obj, "", "    ")
	if nil != err {
		fmt.Println("Error: ", err)
		return ""
	}
	return string(data)
}

func Print(line string) {
	fmt.Println(line)
}

func Join(values ...string) string {
	var buffer bytes.Buffer
	for _, value := range values {
		buffer.WriteString(value)
	}
	return buffer.String()
}

func SetResult(l ASNLexer, v VALUE) {
	l.(*Parser).Result = JSON(&v)
}

type Empty struct{}
type (
	VALUE   interface{}
	STRING  string
	NUMBER  float64
	BOOLEAN bool
	LIST    []VALUE
	MAP     map[string]VALUE
)

//line asn.y:51
type ASNSymType struct {
	yys         int
	TypeToken   struct{}
	TypeString  STRING
	TypeNumber  NUMBER
	TypeValue   VALUE
	TypeBoolean BOOLEAN
	TypeMap     MAP
	TypeList    LIST
}

const CURLY_START = 57346
const CURLY_END = 57347
const SQUARE_START = 57348
const SQUARE_END = 57349
const DOUBLE_QUOTE = 57350
const SINGLE_QUOTE = 57351
const COMMA = 57352
const COLON = 57353
const MINUS = 57354
const GREATER_THAN = 57355
const LESS_THAN = 57356
const DOT = 57357
const SLASH = 57358
const ROUND_START = 57359
const ROUND_END = 57360
const EQUALITY = 57361
const APOSTROPHE = 57362
const SPACE = 57363
const PIPE = 57364
const AT_THE_RATE = 57365
const EXCLAMATION = 57366
const CARET = 57367
const SEMI_COMMA = 57368
const SLASH_B = 57369
const SLASH_H = 57370
const ABSENT_SYMBOL = 57371
const ABSTRACTSYNTAX_SYMBOL = 57372
const ALL_SYMBOL = 57373
const APPLICATION_SYMBOL = 57374
const AUTOMATIC_SYMBOL = 57375
const BEGIN_SYMBOL = 57376
const BIT_SYMBOL = 57377
const BMPSTRING_SYMBOL = 57378
const BOOLEAN_SYMBOL = 57379
const BY_SYMBOL = 57380
const CHARACTER_SYMBOL = 57381
const CHOICE_SYMBOL = 57382
const CLASS_SYMBOL = 57383
const COMPONENT_SYMBOL = 57384
const COMPONENTS_SYMBOL = 57385
const CONSTRAINED_SYMBOL = 57386
const CONTAINING_SYMBOL = 57387
const DATE_SYMBOL = 57388
const DATETIME_SYMBOL = 57389
const DEFAULT_SYMBOL = 57390
const DEFINITIONS_SYMBOL = 57391
const DURATION_SYMBOL = 57392
const EMBEDDED_SYMBOL = 57393
const ENCODED_SYMBOL = 57394
const ENCODINGCONTROL_SYMBOL = 57395
const END_SYMBOL = 57396
const ENUMERATED_SYMBOL = 57397
const EXCEPT_SYMBOL = 57398
const EXPLICIT_SYMBOL = 57399
const EXPORTS_SYMBOL = 57400
const EXTENSIBILITY_SYMBOL = 57401
const EXTERNEL_SYMBOL = 57402
const FALSE_SYMBOL = 57403
const FROM_SYMBOL = 57404
const GENERALIZEDTIME_SYMBOL = 57405
const GENERALSTRING_SYMBOL = 57406
const GRAPHICSTRING_SYMBOL = 57407
const IA5STRING_SYMBOL = 57408
const IDENTIFIER_SYMBOL = 57409
const IMPLICIT_SYMBOL = 57410
const IMPLIED_SYMBOL = 57411
const IMPORTS_SYMBOL = 57412
const INCLUDES_SYMBOL = 57413
const INSTANCE_SYMBOL = 57414
const INSTRUCTIONS_SYMBOL = 57415
const INTEGER_SYMBOL = 57416
const INTERSECTION_SYMBOL = 57417
const ISO646STRING_SYMBOL = 57418
const MAX_SYMBOL = 57419
const MIN_SYMBOL = 57420
const MINUSINFINITY_SYMBOL = 57421
const NOTANUMBER_SYMBOL = 57422
const NULL_SYMBOL = 57423
const NUMERICSTRING_SYMBOL = 57424
const OBJECT_SYMBOL = 57425
const OBJECTDESCRIPTOR_SYMBOL = 57426
const OCTET_SYMBOL = 57427
const OF_SYMBOL = 57428
const OIDIRI_SYMBOL = 57429
const OPTIONAL_SYMBOL = 57430
const PATTERN_SYMBOL = 57431
const PDV_SYMBOL = 57432
const PLUSINFINITY_SYMBOL = 57433
const PRESENT_SYMBOL = 57434
const PRINTABLESTRING_SYMBOL = 57435
const PRIVATE_SYMBOL = 57436
const REAL_SYMBOL = 57437
const RELATIVEOID_SYMBOL = 57438
const RELATIVEOIDIRI_SYMBOL = 57439
const SEQUENCE_SYMBOL = 57440
const SET_SYMBOL = 57441
const SETTINGS_SYMBOL = 57442
const SIZE_SYMBOL = 57443
const STRING_SYMBOL = 57444
const SYNTAX_SYMBOL = 57445
const T61STRING_SYMBOL = 57446
const TAGS_SYMBOL = 57447
const TELETEXSTRING_SYMBOL = 57448
const TIME_SYMBOL = 57449
const TIMEOFDAY_SYMBOL = 57450
const TRUE_SYMBOL = 57451
const TYPEIDENTIFIER_SYMBOL = 57452
const UNION_SYMBOL = 57453
const UNIQUE_SYMBOL = 57454
const UNIVERSAL_SYMBOL = 57455
const UNIVERSALSTRING_SYMBOL = 57456
const UTCTIME_SYMBOL = 57457
const UTF8STRING_SYMBOL = 57458
const VIDEOTEXSTRING_SYMBOL = 57459
const VISIBLESTRING_SYMBOL = 57460
const WITH_SYMBOL = 57461
const ASSIGNMENT_SYMBOL = 57462
const TokenCapitalString = 57463
const TokenString = 57464
const TokenNumber = 57465
const TokenBoolean = 57466

var ASNToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"CURLY_START",
	"CURLY_END",
	"SQUARE_START",
	"SQUARE_END",
	"DOUBLE_QUOTE",
	"SINGLE_QUOTE",
	"COMMA",
	"COLON",
	"MINUS",
	"GREATER_THAN",
	"LESS_THAN",
	"DOT",
	"SLASH",
	"ROUND_START",
	"ROUND_END",
	"EQUALITY",
	"APOSTROPHE",
	"SPACE",
	"PIPE",
	"AT_THE_RATE",
	"EXCLAMATION",
	"CARET",
	"SEMI_COMMA",
	"SLASH_B",
	"SLASH_H",
	"ABSENT_SYMBOL",
	"ABSTRACTSYNTAX_SYMBOL",
	"ALL_SYMBOL",
	"APPLICATION_SYMBOL",
	"AUTOMATIC_SYMBOL",
	"BEGIN_SYMBOL",
	"BIT_SYMBOL",
	"BMPSTRING_SYMBOL",
	"BOOLEAN_SYMBOL",
	"BY_SYMBOL",
	"CHARACTER_SYMBOL",
	"CHOICE_SYMBOL",
	"CLASS_SYMBOL",
	"COMPONENT_SYMBOL",
	"COMPONENTS_SYMBOL",
	"CONSTRAINED_SYMBOL",
	"CONTAINING_SYMBOL",
	"DATE_SYMBOL",
	"DATETIME_SYMBOL",
	"DEFAULT_SYMBOL",
	"DEFINITIONS_SYMBOL",
	"DURATION_SYMBOL",
	"EMBEDDED_SYMBOL",
	"ENCODED_SYMBOL",
	"ENCODINGCONTROL_SYMBOL",
	"END_SYMBOL",
	"ENUMERATED_SYMBOL",
	"EXCEPT_SYMBOL",
	"EXPLICIT_SYMBOL",
	"EXPORTS_SYMBOL",
	"EXTENSIBILITY_SYMBOL",
	"EXTERNEL_SYMBOL",
	"FALSE_SYMBOL",
	"FROM_SYMBOL",
	"GENERALIZEDTIME_SYMBOL",
	"GENERALSTRING_SYMBOL",
	"GRAPHICSTRING_SYMBOL",
	"IA5STRING_SYMBOL",
	"IDENTIFIER_SYMBOL",
	"IMPLICIT_SYMBOL",
	"IMPLIED_SYMBOL",
	"IMPORTS_SYMBOL",
	"INCLUDES_SYMBOL",
	"INSTANCE_SYMBOL",
	"INSTRUCTIONS_SYMBOL",
	"INTEGER_SYMBOL",
	"INTERSECTION_SYMBOL",
	"ISO646STRING_SYMBOL",
	"MAX_SYMBOL",
	"MIN_SYMBOL",
	"MINUSINFINITY_SYMBOL",
	"NOTANUMBER_SYMBOL",
	"NULL_SYMBOL",
	"NUMERICSTRING_SYMBOL",
	"OBJECT_SYMBOL",
	"OBJECTDESCRIPTOR_SYMBOL",
	"OCTET_SYMBOL",
	"OF_SYMBOL",
	"OIDIRI_SYMBOL",
	"OPTIONAL_SYMBOL",
	"PATTERN_SYMBOL",
	"PDV_SYMBOL",
	"PLUSINFINITY_SYMBOL",
	"PRESENT_SYMBOL",
	"PRINTABLESTRING_SYMBOL",
	"PRIVATE_SYMBOL",
	"REAL_SYMBOL",
	"RELATIVEOID_SYMBOL",
	"RELATIVEOIDIRI_SYMBOL",
	"SEQUENCE_SYMBOL",
	"SET_SYMBOL",
	"SETTINGS_SYMBOL",
	"SIZE_SYMBOL",
	"STRING_SYMBOL",
	"SYNTAX_SYMBOL",
	"T61STRING_SYMBOL",
	"TAGS_SYMBOL",
	"TELETEXSTRING_SYMBOL",
	"TIME_SYMBOL",
	"TIMEOFDAY_SYMBOL",
	"TRUE_SYMBOL",
	"TYPEIDENTIFIER_SYMBOL",
	"UNION_SYMBOL",
	"UNIQUE_SYMBOL",
	"UNIVERSAL_SYMBOL",
	"UNIVERSALSTRING_SYMBOL",
	"UTCTIME_SYMBOL",
	"UTF8STRING_SYMBOL",
	"VIDEOTEXSTRING_SYMBOL",
	"VISIBLESTRING_SYMBOL",
	"WITH_SYMBOL",
	"ASSIGNMENT_SYMBOL",
	"TokenCapitalString",
	"TokenString",
	"TokenNumber",
	"TokenBoolean",
}

var ASNStatenames = [...]string{}

const ASNEofCode = 1
const ASNErrCode = 2
const ASNInitialStackSize = 16

//line asn.y:1352

//line yacctab:1
var ASNExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 43,
	54, 27,
	-2, 31,
}

const ASNPrivate = 57344

const ASNLast = 228

var ASNAct = [...]int{
	73, 5, 183, 5, 171, 168, 131, 23, 130, 23,
	23, 188, 62, 32, 29, 21, 59, 61, 21, 23,
	14, 23, 6, 7, 180, 37, 36, 35, 170, 58,
	132, 23, 39, 64, 38, 23, 89, 28, 23, 49,
	48, 27, 41, 83, 34, 49, 56, 51, 57, 63,
	9, 48, 46, 83, 47, 43, 187, 86, 81, 132,
	50, 177, 190, 185, 185, 26, 42, 31, 16, 85,
	40, 177, 44, 12, 3, 165, 25, 8, 1, 164,
	163, 162, 161, 160, 30, 123, 159, 158, 157, 156,
	155, 153, 152, 151, 150, 84, 149, 87, 60, 148,
	53, 52, 82, 80, 147, 146, 88, 145, 59, 144,
	143, 142, 141, 121, 87, 140, 6, 7, 22, 20,
	22, 22, 127, 128, 134, 124, 135, 178, 6, 7,
	22, 20, 22, 172, 137, 173, 154, 136, 133, 169,
	6, 7, 22, 120, 6, 7, 22, 6, 7, 22,
	119, 118, 117, 116, 115, 114, 113, 112, 111, 110,
	109, 108, 107, 106, 105, 104, 102, 103, 179, 182,
	182, 101, 100, 181, 99, 184, 98, 97, 186, 96,
	95, 94, 93, 92, 91, 182, 79, 78, 189, 181,
	77, 76, 75, 74, 167, 166, 90, 126, 125, 139,
	138, 72, 71, 70, 69, 68, 67, 66, 65, 176,
	175, 174, 129, 122, 55, 54, 45, 33, 13, 24,
	19, 18, 17, 15, 11, 10, 4, 2,
}

var ASNPact = [...]int{
	-99, -1000, -99, -1000, 1, 69, -1000, -1000, -1000, -101,
	-1000, -1000, -3, 8, -36, 9, -1000, -1000, -1000, -1000,
	50, -1000, -1000, -110, -15, -78, -79, -80, -1000, -1000,
	-1000, -2, -1000, 59, -27, -1000, -1000, -1000, 48, 21,
	61, -1000, -1000, -19, 41, -7, -13, -30, -106, -14,
	-1000, -1000, -99, -99, 32, -106, -1000, 33, -1000, -1000,
	43, 31, -1000, -99, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 59, -1000, -1000, -1000, -1000, -1000, -1000,
	-99, -1000, -1000, -106, -99, -1000, -1000, -1000, -1000, 59,
	59, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 26, -1000, -1000, -1000, 55, -1000, -1000,
	-1000, -1000, 23, -1000, 56, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -2, -1000, -1000, 19, -5,
	-1000, -1000, 46, -1000, -1000, -1000, -1000, -99, -1000, 29,
	-1000, -1000, 47, -1000, 7, -2, -1000, -1000, -1000, 44,
	-1000,
}

var ASNPgo = [...]int{
	0, 227, 74, 226, 225, 224, 223, 68, 222, 221,
	220, 219, 218, 217, 216, 52, 54, 215, 214, 46,
	48, 29, 213, 212, 8, 5, 4, 211, 210, 209,
	49, 33, 6, 208, 207, 206, 205, 204, 203, 202,
	201, 36, 200, 199, 198, 197, 196, 195, 194, 193,
	192, 191, 190, 187, 186, 184, 183, 182, 181, 180,
	179, 177, 176, 174, 172, 171, 167, 166, 165, 164,
	163, 162, 161, 160, 159, 158, 157, 156, 155, 154,
	153, 152, 151, 150, 143, 138, 137, 134, 127, 115,
	112, 111, 110, 109, 107, 105, 104, 99, 96, 94,
	93, 92, 91, 90, 89, 88, 87, 86, 83, 82,
	81, 80, 79, 32, 0, 2, 78,
}

var ASNR1 = [...]int{
	0, 116, 1, 1, 2, 3, 12, 12, 4, 4,
	5, 6, 6, 7, 7, 7, 8, 9, 10, 11,
	11, 11, 11, 13, 13, 14, 14, 14, 16, 16,
	16, 16, 20, 20, 21, 15, 15, 17, 17, 18,
	18, 19, 22, 23, 23, 23, 24, 24, 24, 25,
	25, 26, 26, 26, 27, 28, 28, 29, 30, 30,
	30, 31, 31, 31, 31, 31, 31, 31, 31, 33,
	34, 35, 36, 37, 38, 39, 40, 40, 40, 40,
	40, 40, 41, 41, 41, 42, 42, 42, 89, 89,
	89, 89, 89, 89, 89, 89, 89, 89, 89, 89,
	89, 89, 89, 89, 89, 89, 89, 89, 89, 89,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 24, 103, 104, 105, 106, 107, 108, 109, 110,
	111, 112, 90, 91, 44, 43, 45, 46, 47, 48,
	49, 50, 51, 52, 53, 54, 32, 32, 32, 32,
	85, 86, 87, 88, 55, 55, 55, 55, 55, 55,
	55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
	55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
	55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
	65, 67, 66, 68, 69, 70, 71, 72, 73, 74,
	75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
	114, 114, 115, 115, 113,
}

var ASNR2 = [...]int{
	0, 1, 1, 2, 9, 2, 2, 0, 1, 0,
	3, 1, 2, 1, 1, 1, 1, 1, 4, 2,
	2, 2, 0, 2, 0, 3, 3, 0, 3, 3,
	2, 0, 1, 3, 1, 3, 0, 1, 0, 1,
	2, 3, 2, 1, 1, 0, 3, 4, 2, 1,
	2, 1, 1, 1, 1, 1, 1, 4, 1, 2,
	0, 1, 1, 1, 1, 1, 1, 1, 1, 3,
	4, 3, 4, 3, 4, 4, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	3, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
	3, 2, 0, 0, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	1, 1, 1, 2, 3,
}

var ASNChk = [...]int{
	-1000, -116, -1, -2, -3, -114, 121, 122, -2, 49,
	-4, -5, 4, -12, 121, -6, -7, -8, -9, -10,
	122, -115, 123, 12, -11, 68, 57, 33, 73, 5,
	-7, 17, 123, -13, 59, 105, 105, 105, -115, -113,
	11, 69, 18, 34, 11, -14, -15, -16, 70, 58,
	19, 54, -16, -15, -17, -18, -19, -20, -21, 122,
	-20, 31, 26, -30, -31, -33, -34, -35, -36, -37,
	-38, -39, -40, -114, -49, -50, -51, -52, -53, -54,
	-30, 26, -19, 10, 62, 26, 26, -31, -113, -41,
	-46, -55, -56, -57, -58, -59, -60, -61, -62, -63,
	-64, -65, -67, -66, -68, -69, -70, -71, -72, -73,
	-74, -75, -76, -77, -78, -79, -80, -81, -82, -83,
	-84, -21, -22, -114, -41, -44, -45, -113, -113, -23,
	-24, -32, 4, -85, -114, -115, -86, -87, -42, -43,
	-89, -90, -91, -92, -93, -94, -95, -96, -97, -98,
	-99, -100, -101, -102, -24, -103, -104, -105, -106, -107,
	-108, -109, -110, -111, -112, 20, -47, -48, -25, -32,
	5, -26, -114, -115, -27, -28, -29, 15, -88, -115,
	5, -26, -114, -115, -25, 17, -114, 27, 4, -115,
	18,
}

var ASNDef = [...]int{
	0, -2, 1, 2, 0, 9, 210, 211, 3, 7,
	5, 8, 0, 22, 0, 0, 11, 13, 14, 15,
	16, 17, 212, 0, 24, 0, 0, 0, 6, 10,
	12, 0, 213, 0, 0, 19, 20, 21, 0, 0,
	0, 23, 18, -2, 0, 0, 31, 36, 38, 0,
	214, 4, 60, 60, 0, 37, 39, 0, 32, 34,
	0, 0, 30, 25, 58, 61, 62, 63, 64, 65,
	66, 67, 68, 0, 76, 77, 78, 79, 80, 81,
	26, 35, 40, 0, 0, 28, 29, 59, 134, 0,
	0, 82, 83, 84, 154, 155, 156, 157, 158, 159,
	160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
	170, 171, 172, 173, 174, 175, 176, 177, 178, 179,
	180, 33, 41, 45, 69, 71, 73, 111, 138, 42,
	43, 44, 0, 146, 147, 148, 149, 153, 70, 72,
	85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
	95, 96, 97, 98, 99, 100, 101, 102, 103, 104,
	105, 106, 107, 108, 109, 0, 74, 75, 0, 0,
	48, 49, 54, 55, 51, 52, 53, 0, 151, 0,
	46, 50, 54, 55, 0, 0, 150, 110, 47, 0,
	57,
}

var ASNTok1 = [...]int{
	1,
}

var ASNTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124,
}

var ASNTok3 = [...]int{
	0,
}

var ASNErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	ASNDebug        = 0
	ASNErrorVerbose = false
)

type ASNLexer interface {
	Lex(lval *ASNSymType) int
	Error(s string)
}

type ASNParser interface {
	Parse(ASNLexer) int
	Lookahead() int
}

type ASNParserImpl struct {
	lval  ASNSymType
	stack [ASNInitialStackSize]ASNSymType
	char  int
}

func (p *ASNParserImpl) Lookahead() int {
	return p.char
}

func ASNNewParser() ASNParser {
	return &ASNParserImpl{}
}

const ASNFlag = -1000

func ASNTokname(c int) string {
	if c >= 1 && c-1 < len(ASNToknames) {
		if ASNToknames[c-1] != "" {
			return ASNToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func ASNStatname(s int) string {
	if s >= 0 && s < len(ASNStatenames) {
		if ASNStatenames[s] != "" {
			return ASNStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func ASNErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !ASNErrorVerbose {
		return "syntax error"
	}

	for _, e := range ASNErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + ASNTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := ASNPact[state]
	for tok := TOKSTART; tok-1 < len(ASNToknames); tok++ {
		if n := base + tok; n >= 0 && n < ASNLast && ASNChk[ASNAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if ASNDef[state] == -2 {
		i := 0
		for ASNExca[i] != -1 || ASNExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; ASNExca[i] >= 0; i += 2 {
			tok := ASNExca[i]
			if tok < TOKSTART || ASNExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if ASNExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += ASNTokname(tok)
	}
	return res
}

func ASNlex1(lex ASNLexer, lval *ASNSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = ASNTok1[0]
		goto out
	}
	if char < len(ASNTok1) {
		token = ASNTok1[char]
		goto out
	}
	if char >= ASNPrivate {
		if char < ASNPrivate+len(ASNTok2) {
			token = ASNTok2[char-ASNPrivate]
			goto out
		}
	}
	for i := 0; i < len(ASNTok3); i += 2 {
		token = ASNTok3[i+0]
		if token == char {
			token = ASNTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = ASNTok2[1] /* unknown char */
	}
	if ASNDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", ASNTokname(token), uint(char))
	}
	return char, token
}

func ASNParse(ASNlex ASNLexer) int {
	return ASNNewParser().Parse(ASNlex)
}

func (ASNrcvr *ASNParserImpl) Parse(ASNlex ASNLexer) int {
	var ASNn int
	var ASNVAL ASNSymType
	var ASNDollar []ASNSymType
	_ = ASNDollar // silence set and not used
	ASNS := ASNrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	ASNstate := 0
	ASNrcvr.char = -1
	ASNtoken := -1 // ASNrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		ASNstate = -1
		ASNrcvr.char = -1
		ASNtoken = -1
	}()
	ASNp := -1
	goto ASNstack

ret0:
	return 0

ret1:
	return 1

ASNstack:
	/* put a state and value onto the stack */
	if ASNDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", ASNTokname(ASNtoken), ASNStatname(ASNstate))
	}

	ASNp++
	if ASNp >= len(ASNS) {
		nyys := make([]ASNSymType, len(ASNS)*2)
		copy(nyys, ASNS)
		ASNS = nyys
	}
	ASNS[ASNp] = ASNVAL
	ASNS[ASNp].yys = ASNstate

ASNnewstate:
	ASNn = ASNPact[ASNstate]
	if ASNn <= ASNFlag {
		goto ASNdefault /* simple state */
	}
	if ASNrcvr.char < 0 {
		ASNrcvr.char, ASNtoken = ASNlex1(ASNlex, &ASNrcvr.lval)
	}
	ASNn += ASNtoken
	if ASNn < 0 || ASNn >= ASNLast {
		goto ASNdefault
	}
	ASNn = ASNAct[ASNn]
	if ASNChk[ASNn] == ASNtoken { /* valid shift */
		ASNrcvr.char = -1
		ASNtoken = -1
		ASNVAL = ASNrcvr.lval
		ASNstate = ASNn
		if Errflag > 0 {
			Errflag--
		}
		goto ASNstack
	}

ASNdefault:
	/* default state action */
	ASNn = ASNDef[ASNstate]
	if ASNn == -2 {
		if ASNrcvr.char < 0 {
			ASNrcvr.char, ASNtoken = ASNlex1(ASNlex, &ASNrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if ASNExca[xi+0] == -1 && ASNExca[xi+1] == ASNstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			ASNn = ASNExca[xi+0]
			if ASNn < 0 || ASNn == ASNtoken {
				break
			}
		}
		ASNn = ASNExca[xi+1]
		if ASNn < 0 {
			goto ret0
		}
	}
	if ASNn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			ASNlex.Error(ASNErrorMessage(ASNstate, ASNtoken))
			Nerrs++
			if ASNDebug >= 1 {
				__yyfmt__.Printf("%s", ASNStatname(ASNstate))
				__yyfmt__.Printf(" saw %s\n", ASNTokname(ASNtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for ASNp >= 0 {
				ASNn = ASNPact[ASNS[ASNp].yys] + ASNErrCode
				if ASNn >= 0 && ASNn < ASNLast {
					ASNstate = ASNAct[ASNn] /* simulate a shift of "error" */
					if ASNChk[ASNstate] == ASNErrCode {
						goto ASNstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if ASNDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", ASNS[ASNp].yys)
				}
				ASNp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if ASNDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", ASNTokname(ASNtoken))
			}
			if ASNtoken == ASNEofCode {
				goto ret1
			}
			ASNrcvr.char = -1
			ASNtoken = -1
			goto ASNnewstate /* try again in the same state */
		}
	}

	/* reduction by production ASNn */
	if ASNDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", ASNn, ASNStatname(ASNstate))
	}

	ASNnt := ASNn
	ASNpt := ASNp
	_ = ASNpt // guard against "declared and not used"

	ASNp -= ASNR2[ASNn]
	// ASNp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if ASNp+1 >= len(ASNS) {
		nyys := make([]ASNSymType, len(ASNS)*2)
		copy(nyys, ASNS)
		ASNS = nyys
	}
	ASNVAL = ASNS[ASNp+1]

	/* consult goto table to find next state */
	ASNn = ASNR1[ASNn]
	ASNg := ASNPgo[ASNn]
	ASNj := ASNg + ASNS[ASNp].yys + 1

	if ASNj >= ASNLast {
		ASNstate = ASNAct[ASNg]
	} else {
		ASNstate = ASNAct[ASNj]
		if ASNChk[ASNstate] != -ASNn {
			ASNstate = ASNAct[ASNg]
		}
	}
	// dummy call; replaced with literal code
	switch ASNnt {

	case 1:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:308
		{
			SetResult(ASNlex, ASNDollar[1].TypeValue)
			Print("Done")
			Print("--------------------------------------------------------------------------------")
			Print(JSON(&ASNDollar[1].TypeValue))
			Print("--------------------------------------------------------------------------------")
		}
	case 2:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:317
		{
			ASNVAL.TypeValue = LIST{
				ASNDollar[1].TypeValue,
			}
		}
	case 3:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:322
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
			ASNVAL.TypeValue = append(ASNVAL.TypeValue.(LIST), ASNDollar[2].TypeValue)
		}
	case 4:
		ASNDollar = ASNS[ASNpt-9 : ASNpt+1]
//line asn.y:337
		{
			ASNVAL.TypeValue = MAP{
				"identifier": ASNDollar[1].TypeValue,
				"encoding":   ASNDollar[3].TypeValue,
				"tag":        ASNDollar[4].TypeValue,
				"body":       ASNDollar[8].TypeValue,
			}
		}
	case 5:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:349
		{
			ASNVAL.TypeValue = MAP{
				"reference":             ASNDollar[1].TypeValue,
				"definitiveIdentifiers": ASNDollar[2].TypeValue,
			}
		}
	case 6:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:357
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeString
		}
	case 7:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:360
		{
			ASNVAL.TypeValue = ""
		}
	case 8:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:365
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 9:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:368
		{
			ASNVAL.TypeValue = nil
		}
	case 10:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:373
		{
			ASNVAL.TypeValue = ASNDollar[2].TypeValue
		}
	case 11:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:378
		{
			ASNVAL.TypeValue = LIST{
				ASNDollar[1].TypeValue,
			}
		}
	case 12:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:383
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
			ASNVAL.TypeValue = append(ASNVAL.TypeValue.(LIST), ASNDollar[2].TypeValue)
		}
	case 13:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:389
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 14:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:392
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 15:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:395
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 16:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:400
		{
			ASNVAL.TypeValue = MAP{
				"name": ASNDollar[1].TypeString,
			}
		}
	case 17:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:407
		{
			ASNVAL.TypeValue = MAP{
				"number": ASNDollar[1].TypeValue,
			}
		}
	case 18:
		ASNDollar = ASNS[ASNpt-4 : ASNpt+1]
//line asn.y:414
		{
			ASNVAL.TypeValue = MAP{
				"name":   ASNDollar[1].TypeString,
				"number": ASNDollar[3].TypeValue,
			}
		}
	case 19:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:422
		{
			ASNVAL.TypeValue = "Implicit"
		}
	case 20:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:425
		{
			ASNVAL.TypeValue = "Explicit"
		}
	case 21:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:428
		{
			ASNVAL.TypeValue = "Automatic"
		}
	case 22:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:431
		{
			ASNVAL.TypeValue = "Explicit"
		}
	case 23:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:436
		{
			ASNVAL.TypeValue = true
		}
	case 24:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:439
		{
			ASNVAL.TypeValue = false
		}
	case 25:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:446
		{
			ASNVAL.TypeValue = MAP{
				"imports":     ASNDollar[1].TypeValue,
				"exports":     ASNDollar[2].TypeValue,
				"assignments": ASNDollar[3].TypeValue,
			}
		}
	case 26:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:455
		{
			ASNVAL.TypeValue = MAP{
				"imports":     ASNDollar[2].TypeValue,
				"exports":     ASNDollar[1].TypeValue,
				"assignments": ASNDollar[3].TypeValue,
			}
		}
	case 27:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:462
		{
			ASNVAL.TypeValue = nil
		}
	case 28:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:467
		{
			ASNVAL.TypeValue = MAP{
				"all":     "false",
				"symbols": ASNDollar[2].TypeValue,
			}
		}
	case 29:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:473
		{
			ASNVAL.TypeValue = MAP{
				"all": "true",
			}
		}
	case 30:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:478
		{
			ASNVAL.TypeValue = MAP{
				"all": "false",
			}
		}
	case 31:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:483
		{
			ASNVAL.TypeValue = MAP{
				"all": "true",
			}
		}
	case 32:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:490
		{
			ASNVAL.TypeValue = LIST{
				ASNDollar[1].TypeValue,
			}
		}
	case 33:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:495
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
			ASNVAL.TypeValue = append(ASNVAL.TypeValue.(LIST), ASNDollar[3].TypeValue)
		}
	case 34:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:501
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeString
		}
	case 35:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:506
		{
			ASNVAL.TypeValue = ASNDollar[2].TypeValue
		}
	case 36:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:509
		{
			ASNVAL.TypeValue = nil
		}
	case 37:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:514
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 38:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:517
		{
			ASNVAL.TypeValue = nil
		}
	case 39:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:522
		{
			ASNVAL.TypeValue = LIST{
				ASNDollar[1].TypeValue,
			}
		}
	case 40:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:527
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
			ASNVAL.TypeValue = append(ASNVAL.TypeValue.(LIST), ASNDollar[2].TypeValue)
		}
	case 41:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:533
		{
			ASNVAL.TypeValue = MAP{
				"symbols":   ASNDollar[1].TypeValue,
				"reference": ASNDollar[3].TypeValue,
			}
		}
	case 42:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:541
		{
			ASNVAL.TypeValue = MAP{
				"name":        ASNDollar[1].TypeValue,
				"identifiers": ASNDollar[2].TypeValue,
			}
		}
	case 43:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:549
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 44:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:552
		{
			ASNVAL.TypeValue = nil
		}
	case 45:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:555
		{
			ASNVAL.TypeValue = nil
		}
	case 46:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:560
		{
			ASNVAL.TypeValue = ASNDollar[2].TypeValue
		}
	case 47:
		ASNDollar = ASNS[ASNpt-4 : ASNpt+1]
//line asn.y:563
		{
			ASNVAL.TypeValue = ASNDollar[3].TypeValue
		}
	case 48:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:566
		{
			ASNVAL.TypeValue = nil
		}
	case 49:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:571
		{
			ASNVAL.TypeValue = LIST{
				ASNDollar[1].TypeValue,
			}
		}
	case 50:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:576
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
			ASNVAL.TypeValue = append(ASNVAL.TypeValue.(LIST), ASNDollar[2].TypeValue)
		}
	case 51:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:582
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 52:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:585
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 53:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:588
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 54:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:593
		{
			ASNVAL.TypeValue = MAP{
				"name": ASNDollar[1].TypeValue,
			}
		}
	case 55:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:600
		{
			ASNVAL.TypeValue = MAP{
				"number": ASNDollar[1].TypeValue,
			}
		}
	case 56:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:605
		{
			ASNVAL.TypeValue = MAP{
				"number": ASNDollar[1].TypeValue,
			}
		}
	case 57:
		ASNDollar = ASNS[ASNpt-4 : ASNpt+1]
//line asn.y:612
		{
			ASNVAL.TypeValue = MAP{
				"name":   ASNDollar[1].TypeValue,
				"number": ASNDollar[3].TypeValue,
			}
		}
	case 58:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:620
		{
			ASNVAL.TypeValue = LIST{
				ASNDollar[1].TypeValue,
			}
		}
	case 59:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:625
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
			ASNVAL.TypeValue = append(ASNVAL.TypeValue.(LIST), ASNDollar[2].TypeValue)
		}
	case 60:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:629
		{
			ASNVAL.TypeValue = nil
		}
	case 61:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:634
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 62:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:637
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 63:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:640
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 64:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:643
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 65:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:646
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 66:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:649
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 67:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:652
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 68:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:655
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 69:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:660
		{
			ASNVAL.TypeValue = MAP{
				"assignment": "TYPE",
				"reference":  ASNDollar[1].TypeValue,
				"type":       ASNDollar[2].TypeValue,
			}
		}
	case 70:
		ASNDollar = ASNS[ASNpt-4 : ASNpt+1]
//line asn.y:669
		{
			ASNVAL.TypeValue = MAP{
				"assignment": "VALUE",
				"reference":  ASNDollar[1].TypeValue,
				"type":       ASNDollar[2].TypeValue,
				"value":      ASNDollar[4].TypeValue,
			}
		}
	case 71:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:679
		{
			ASNVAL.TypeValue = MAP{
				"assignment": "XML_VALUE",
				"reference":  ASNDollar[1].TypeValue,
				"value":      ASNDollar[3].TypeValue,
			}
		}
	case 72:
		ASNDollar = ASNS[ASNpt-4 : ASNpt+1]
//line asn.y:688
		{
			ASNVAL.TypeValue = MAP{
				"assignment": "VALUE_SET",
				"reference":  ASNDollar[1].TypeValue,
				"type":       ASNDollar[2].TypeValue,
				"values":     ASNDollar[4].TypeValue,
			}
		}
	case 73:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:698
		{
			ASNVAL.TypeValue = MAP{
				"assignment": "OBJECT_CLASS",
				"reference":  ASNDollar[1].TypeValue,
				"class":      ASNDollar[3].TypeValue,
			}
		}
	case 74:
		ASNDollar = ASNS[ASNpt-4 : ASNpt+1]
//line asn.y:707
		{
			ASNVAL.TypeValue = MAP{
				"assignment": "OBJECT",
				"reference":  ASNDollar[1].TypeValue,
				"class":      ASNDollar[2].TypeValue,
				"value":      ASNDollar[4].TypeValue,
			}
		}
	case 75:
		ASNDollar = ASNS[ASNpt-4 : ASNpt+1]
//line asn.y:717
		{
			ASNVAL.TypeValue = MAP{
				"assignment": "OBJECT_SET",
				"reference":  ASNDollar[1].TypeValue,
				"class":      ASNDollar[2].TypeValue,
				"values":     ASNDollar[4].TypeValue,
			}
		}
	case 76:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:727
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 77:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:730
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 78:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:733
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 79:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:736
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 80:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:739
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 81:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:742
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeValue
		}
	case 82:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:747
		{
			ASNVAL.TypeValue = MAP{
				"type":       "BUILTIN_TYPE",
				"properties": ASNDollar[1].TypeValue,
			}
		}
	case 83:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:753
		{
			ASNVAL.TypeValue = MAP{
				"type":       "REFERENCED_TYPE",
				"properties": ASNDollar[1].TypeValue,
			}
		}
	case 84:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:759
		{
			ASNVAL.TypeValue = MAP{
				"type":       "CONSTRAINED_TYPE",
				"properties": ASNDollar[1].TypeValue,
			}
		}
	case 85:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:767
		{
			ASNVAL.TypeValue = MAP{
				"type":       "BUILTIN_VALUE",
				"properties": ASNDollar[1].TypeValue,
			}
		}
	case 86:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:773
		{
			ASNVAL.TypeValue = MAP{
				"type":       "REFERENCED_VALUE",
				"properties": ASNDollar[1].TypeValue,
			}
		}
	case 87:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:779
		{
			ASNVAL.TypeValue = MAP{
				"type":       "OBJECT_CLASS_FIELD_VALUE",
				"properties": ASNDollar[1].TypeValue,
			}
		}
	case 88:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:787
		{
			ASNVAL.TypeValue = MAP{
				"bitString": ASNDollar[1].TypeValue,
			}
		}
	case 89:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:792
		{
			ASNVAL.TypeValue = MAP{
				"boolean": ASNDollar[1].TypeValue,
			}
		}
	case 90:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:797
		{
			ASNVAL.TypeValue = MAP{
				"characterString": ASNDollar[1].TypeValue,
			}
		}
	case 91:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:802
		{
			ASNVAL.TypeValue = MAP{
				"choice": ASNDollar[1].TypeValue,
			}
		}
	case 92:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:807
		{
			ASNVAL.TypeValue = MAP{
				"embeddedPDV": ASNDollar[1].TypeValue,
			}
		}
	case 93:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:812
		{
			ASNVAL.TypeValue = MAP{
				"enumerated": ASNDollar[1].TypeValue,
			}
		}
	case 94:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:817
		{
			ASNVAL.TypeValue = MAP{
				"external": ASNDollar[1].TypeValue,
			}
		}
	case 95:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:822
		{
			ASNVAL.TypeValue = MAP{
				"instanceOf": ASNDollar[1].TypeValue,
			}
		}
	case 96:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:827
		{
			ASNVAL.TypeValue = MAP{
				"integer": ASNDollar[1].TypeValue,
			}
		}
	case 97:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:832
		{
			ASNVAL.TypeValue = MAP{
				"iri": ASNDollar[1].TypeValue,
			}
		}
	case 98:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:837
		{
			ASNVAL.TypeValue = MAP{
				"null": ASNDollar[1].TypeValue,
			}
		}
	case 99:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:842
		{
			ASNVAL.TypeValue = MAP{
				"objectIdentifier": ASNDollar[1].TypeValue,
			}
		}
	case 100:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:847
		{
			ASNVAL.TypeValue = MAP{
				"octetString": ASNDollar[1].TypeValue,
			}
		}
	case 101:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:852
		{
			ASNVAL.TypeValue = MAP{
				"real": ASNDollar[1].TypeValue,
			}
		}
	case 102:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:857
		{
			ASNVAL.TypeValue = MAP{
				"relativeIRI": ASNDollar[1].TypeValue,
			}
		}
	case 103:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:862
		{
			ASNVAL.TypeValue = MAP{
				"relativeOID": ASNDollar[1].TypeValue,
			}
		}
	case 104:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:867
		{
			ASNVAL.TypeValue = MAP{
				"sequence": ASNDollar[1].TypeValue,
			}
		}
	case 105:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:872
		{
			ASNVAL.TypeValue = MAP{
				"sequenceOf": ASNDollar[1].TypeValue,
			}
		}
	case 106:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:877
		{
			ASNVAL.TypeValue = MAP{
				"set": ASNDollar[1].TypeValue,
			}
		}
	case 107:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:882
		{
			ASNVAL.TypeValue = MAP{
				"setOf": ASNDollar[1].TypeValue,
			}
		}
	case 108:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:887
		{
			ASNVAL.TypeValue = MAP{
				"prefixed": ASNDollar[1].TypeValue,
			}
		}
	case 109:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:892
		{
			ASNVAL.TypeValue = MAP{
				"time": ASNDollar[1].TypeValue,
			}
		}
	case 110:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:899
		{
			ASNVAL.TypeValue = strconv.FormatFloat(ASNDollar[2].TypeValue.(float64), 'f', -1, 64)
		}
	case 111:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:904
		{
			ASNVAL.TypeValue = nil
		}
	case 112:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:908
		{
			ASNVAL.TypeValue = nil
		}
	case 113:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:912
		{
			ASNVAL.TypeValue = nil
		}
	case 114:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:916
		{
			ASNVAL.TypeValue = nil
		}
	case 115:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:920
		{
			ASNVAL.TypeValue = nil
		}
	case 116:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:924
		{
			ASNVAL.TypeValue = nil
		}
	case 117:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:928
		{
			ASNVAL.TypeValue = nil
		}
	case 118:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:932
		{
			ASNVAL.TypeValue = nil
		}
	case 119:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:936
		{
			ASNVAL.TypeValue = nil
		}
	case 120:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:940
		{
			ASNVAL.TypeValue = nil
		}
	case 121:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:944
		{
			ASNVAL.TypeValue = nil
		}
	case 122:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:948
		{
			ASNVAL.TypeValue = nil
		}
	case 123:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:952
		{
			ASNVAL.TypeValue = nil
		}
	case 124:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:956
		{
			ASNVAL.TypeValue = nil
		}
	case 125:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:960
		{
			ASNVAL.TypeValue = nil
		}
	case 126:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:964
		{
			ASNVAL.TypeValue = nil
		}
	case 127:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:968
		{
			ASNVAL.TypeValue = nil
		}
	case 128:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:972
		{
			ASNVAL.TypeValue = nil
		}
	case 129:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:976
		{
			ASNVAL.TypeValue = nil
		}
	case 130:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:980
		{
			ASNVAL.TypeValue = nil
		}
	case 131:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:984
		{
			ASNVAL.TypeValue = nil
		}
	case 132:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:989
		{
			ASNVAL.TypeValue = nil
		}
	case 133:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:994
		{
			ASNVAL.TypeValue = nil
		}
	case 134:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:999
		{
			ASNVAL.TypeValue = nil
		}
	case 135:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1004
		{
			ASNVAL.TypeValue = nil
		}
	case 136:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1009
		{
			ASNVAL.TypeValue = nil
		}
	case 137:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1014
		{
			ASNVAL.TypeValue = nil
		}
	case 138:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1019
		{
			ASNVAL.TypeValue = nil
		}
	case 139:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1024
		{
			ASNVAL.TypeValue = nil
		}
	case 140:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1029
		{
			ASNVAL.TypeValue = nil
		}
	case 141:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1034
		{
			ASNVAL.TypeValue = nil
		}
	case 142:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1039
		{
			ASNVAL.TypeValue = nil
		}
	case 143:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1044
		{
			ASNVAL.TypeValue = nil
		}
	case 144:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1049
		{
			ASNVAL.TypeValue = nil
		}
	case 145:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1054
		{
			ASNVAL.TypeValue = nil
		}
	case 146:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1059
		{
			ASNVAL.TypeValue = MAP{
				"type":  "EXTERNAL_VALUE",
				"value": ASNDollar[1].TypeValue,
			}
		}
	case 147:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1065
		{
			ASNVAL.TypeValue = MAP{
				"type":  "STRING_VALUE",
				"value": ASNDollar[1].TypeValue,
			}
		}
	case 148:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1071
		{
			ASNVAL.TypeValue = MAP{
				"type":  "NUMBER_VALUE",
				"value": ASNDollar[1].TypeValue,
			}
		}
	case 149:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1077
		{
			ASNVAL.TypeValue = MAP{
				"type":  "PARAMETERIZED_VALUE",
				"value": ASNDollar[1].TypeValue,
			}
		}
	case 150:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:1085
		{
			ASNVAL.TypeValue = MAP{
				"module": ASNDollar[1].TypeValue,
				"value":  ASNDollar[3].TypeValue,
			}
		}
	case 151:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:1093
		{
			ASNVAL.TypeValue = nil
		}
	case 152:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1098
		{
			ASNVAL.TypeValue = nil
		}
	case 153:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1103
		{
			ASNVAL.TypeValue = nil
		}
	case 154:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1108
		{

		}
	case 155:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1111
		{

		}
	case 156:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1114
		{

		}
	case 157:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1117
		{

		}
	case 158:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1120
		{

		}
	case 159:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1123
		{

		}
	case 160:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1126
		{

		}
	case 161:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1129
		{

		}
	case 162:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1132
		{

		}
	case 163:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1135
		{

		}
	case 164:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1138
		{

		}
	case 165:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1141
		{

		}
	case 166:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1144
		{

		}
	case 167:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1147
		{

		}
	case 168:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1150
		{

		}
	case 169:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1153
		{

		}
	case 170:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1156
		{

		}
	case 171:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1159
		{

		}
	case 172:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1162
		{

		}
	case 173:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1165
		{

		}
	case 174:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1168
		{

		}
	case 175:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1171
		{

		}
	case 176:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1174
		{

		}
	case 177:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1177
		{

		}
	case 178:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1180
		{

		}
	case 179:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1183
		{

		}
	case 180:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1186
		{

		}
	case 181:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1191
		{
			ASNVAL.TypeValue = nil
		}
	case 182:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1196
		{
			ASNVAL.TypeValue = nil
		}
	case 183:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1201
		{
			ASNVAL.TypeValue = nil
		}
	case 184:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1206
		{
			ASNVAL.TypeValue = nil
		}
	case 185:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1211
		{
			ASNVAL.TypeValue = nil
		}
	case 186:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1215
		{
			ASNVAL.TypeValue = nil
		}
	case 187:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1220
		{
			ASNVAL.TypeValue = nil
		}
	case 188:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1224
		{
			ASNVAL.TypeValue = nil
		}
	case 189:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1228
		{
			ASNVAL.TypeValue = nil
		}
	case 190:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1233
		{
			ASNVAL.TypeValue = nil
		}
	case 191:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1238
		{
			ASNVAL.TypeValue = nil
		}
	case 192:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1243
		{
			ASNVAL.TypeValue = nil
		}
	case 193:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1248
		{
			ASNVAL.TypeValue = nil
		}
	case 194:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1253
		{
			ASNVAL.TypeValue = nil
		}
	case 195:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1258
		{
			ASNVAL.TypeValue = nil
		}
	case 196:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1263
		{
			ASNVAL.TypeValue = nil
		}
	case 197:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1268
		{
			ASNVAL.TypeValue = nil
		}
	case 198:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1273
		{
			ASNVAL.TypeValue = nil
		}
	case 199:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1278
		{
			ASNVAL.TypeValue = nil
		}
	case 200:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1283
		{
			ASNVAL.TypeValue = nil
		}
	case 201:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1288
		{
			ASNVAL.TypeValue = nil
		}
	case 202:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1293
		{
			ASNVAL.TypeValue = nil
		}
	case 203:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1298
		{
			ASNVAL.TypeValue = nil
		}
	case 204:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1303
		{
			ASNVAL.TypeValue = nil
		}
	case 205:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1308
		{
			ASNVAL.TypeValue = nil
		}
	case 206:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1313
		{
			ASNVAL.TypeValue = nil
		}
	case 207:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1318
		{
			ASNVAL.TypeValue = nil
		}
	case 208:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1323
		{
			ASNVAL.TypeValue = nil
		}
	case 209:
		ASNDollar = ASNS[ASNpt-0 : ASNpt+1]
//line asn.y:1328
		{
			ASNVAL.TypeValue = nil
		}
	case 210:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1333
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeString
		}
	case 211:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1336
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeString
		}
	case 212:
		ASNDollar = ASNS[ASNpt-1 : ASNpt+1]
//line asn.y:1341
		{
			ASNVAL.TypeValue = ASNDollar[1].TypeNumber
		}
	case 213:
		ASNDollar = ASNS[ASNpt-2 : ASNpt+1]
//line asn.y:1344
		{
			ASNVAL.TypeValue = (-1) * ASNDollar[2].TypeNumber
		}
	case 214:
		ASNDollar = ASNS[ASNpt-3 : ASNpt+1]
//line asn.y:1349
		{
			ASNVAL.TypeValue = "::="
		}
	}
	goto ASNstack /* stack new state and value */
}
